language: node_js
node_js:
  - "6"

before_install:
  - npm i -g npm@latest

script:
  - yarn lint
  - yarn test

cache: yarn

deploy:
  provider: npm
  email: $EMAIL
  api_key: $AUTH_TOKEN
  on:
    tags: true
    branch: master