language: node_js
node_js:
  - "8"

script:
  - yarn lint
  - yarn test

cache: yarn

deploy:
  provider: npm
  email: $EMAIL
  api_key: $AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master